# Generated by Django 4.1 on 2022-09-16 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("IndexApp", "0004_message_created_message_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
